- name: WordPress Plugin Deploy
        uses: WordPress/action-deploy-to-wordpress-org@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: kurashi-clutch-admin-notes
